// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWf4AOim52INbNQdPUOSzcUqpOgU04gEo',
    appId: '1:484438549656:web:d9ea51ac62d16bba66dced',
    messagingSenderId: '484438549656',
    projectId: 'smokefreeai-99f98',
    authDomain: 'smokefreeai-99f98.firebaseapp.com',
    storageBucket: 'smokefreeai-99f98.firebasestorage.app',
    measurementId: 'G-LCF957XV70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrSjdgXFyaLoppo8x_tEczXlg5Bdi9Z4',
    appId: '1:484438549656:android:a4b686bac1e4a03366dced',
    messagingSenderId: '484438549656',
    projectId: 'smokefreeai-99f98',
    storageBucket: 'smokefreeai-99f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBABmo2jeiDbo0SpRLoa5QSMYp3wtNXXRU',
    appId: '1:484438549656:ios:41b5658efcec48c666dced',
    messagingSenderId: '484438549656',
    projectId: 'smokefreeai-99f98',
    storageBucket: 'smokefreeai-99f98.firebasestorage.app',
    androidClientId: '484438549656-psmk8cedsbep28vdq0hqv8b4lpo6omeq.apps.googleusercontent.com',
    iosClientId: '484438549656-3lhg8fkbcif0ooel7v5lsl6pohm0nm4b.apps.googleusercontent.com',
    iosBundleId: 'com.smokefree.smokefree',
  );
}
